<?php
/**
 * Sayyor qabul kunlari
 *
 * @author    Muzaffardjan Karaev
 * @copyright Copyright (c) "FOR EACH SOFT" LTD 2015 (http://www.each.uz)
 * @license   "FOR EACH SOFT" LTD PUBLIC LICENSE
 * Created:   09.03.2017
 *
 * @var \Zend\Navigation\Navigation $container
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
?>
<?php foreach ($container as $key => $page) : ?>
<?php
    if ($this->isGranted($page->getPermission())) {
        if ($page instanceof \Zend\Navigation\Page\Mvc) {
            $params = $page->getParams() ? $page->getParams() : [];

            $page->setParams(
                array_merge(
                    $params,
                    ['locale' => $this->locale()->current()]
                )
            );
        }
    }
?>
    <?php if (($page->hasPages() || $page->hasChildren()) && !$page->category) : ?>
        <li class="site-menu-item has-sub <?php echo ($page->getChildren()->isActive()) ? 'active open' : ''; ?>">
            <a href="javascript:void(0);">
                <i class="site-menu-icon wb-<?php echo $page->icon ?>" aria-hidden="true"></i>
                <span class="site-menu-title">
                    <?php echo $this->translate($page->getLabel()) ?>
                </span>
                <span class="site-menu-arrow"></span>
            </a>

            <ul class="site-menu-sub">
                <?php echo $this->partial('admin/partial/menu', ['container' => $page]) ?>
            </ul>
        </li>
    <?php elseif ($page->category) : ?>
        <li class="site-menu-category">
            <?php echo $this->translate($page->getLabel()); ?>
        </li>
    <?php else : ?>
        <li class="site-menu-item <?php echo ($page->isActive()) ? 'active' : ''; ?>">
            <a class="animsition-link" href="<?php echo $page->getHref(); ?>">
                <?php if ($page->icon) : ?>
                    <i class="<?php echo $page->icon ?>" aria-hidden="true"></i>
                <?php endif; ?>

                <span class="site-menu-title">
                    <?php echo $this->translate($page->getLabel()); ?>
                </span>
            </a>
        </li>
    <?php endif; ?>
<?php endforeach; ?>
