<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 */
echo $this->doctype();
?>
<html class="no-js css-menubar" lang="<?php echo substr($this->locale()->current(), 0, 2); ?>">
<head>
    <meta charset="utf-8">
    <?php
    echo $this->headTitle($this->translate('Dashboard'))->setSeparator(' - ')->setAutoEscape(false);
    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
    echo $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath('/img/favicon.ico')])
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:300,400,500,300italic')
        ->prependStylesheet($this->basePath('dist/global/fonts/brand-icons/brand-icons.min.css'))
        ->prependStylesheet($this->basePath('dist/global/fonts/web-icons/web-icons.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/flag-icon-css/flag-icon.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/slidepanel/slidePanel.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/intro-js/introjs.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/switchery/switchery.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/asscrollable/asScrollable.min.css'))
        ->prependStylesheet($this->basePath('dist/global/vendor/animsition/animsition.min.css'))
        ->prependStylesheet($this->basePath('dist/assets/css/site.min.css'))
        ->prependStylesheet($this->basePath('dist/global/css/bootstrap-extend.min.css'))
        ->prependStylesheet($this->basePath('dist/global/css/bootstrap.min.css'));
    ?>
    <!-- Skin tools (demo site only) -->
    <link rel="stylesheet" href="<?php echo $this->basePath('dist/global/vendor/skin-tools/skintools.min.css') ?>">
    <script src="<?php echo $this->basePath('dist/global/vendor/skin-tools/skintools.js') ?>"></script>
    <!--[if lt IE 9]>
    <script src="<?php echo $this->basePath('dist/global/vendor/html5shiv/html5shiv.min.js'); ?>"></script>
    <![endif]-->
    <!--[if lt IE 10]>
    <script src="<?php echo $this->basePath('dist/global/vendor/media-match/media.match.min.js'); ?>"></script>
    <script src="<?php echo $this->basePath('dist/global/vendor/respond/respond.min.js'); ?>"></script>
    <![endif]-->
    <?php
    echo $this->headScript()
        ->prependFile($this->basePath('dist/global/vendor/breakpoints/breakpoints.min.js'))
        ->prependFile($this->basePath('dist/global/vendor/modernizr/modernizr.min.js'))
        ->prependFile($this->basePath('dist/global/vendor/jquery/jquery.min.js'));
    ?>
    <script>Breakpoints();</script>
</head>
<body>
<!--[if lt IE 8]>
<p class="browserupgrade">
    You are using an <strong>outdated</strong> browser.
    Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.
</p>
<![endif]-->

<nav class="site-navbar navbar navbar-default navbar-fixed-top navbar-mega" role="navigation">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle hamburger hamburger-close navbar-toggle-left hided" data-toggle="menubar">
            <span class="sr-only">Toggle navigation</span>
            <span class="hamburger-bar"></span>
        </button>

        <button type="button" class="navbar-toggle collapsed" data-target="#site-navbar-collapse" data-toggle="collapse">
            <i class="icon wb-more-horizontal" aria-hidden="true"></i>
        </button>

        <div class="navbar-brand navbar-brand-center site-gridmenu-toggle" data-toggle="gridmenu">
            <img class="navbar-brand-logo" src="<?php echo $this->basePath('dist/assets/images/logo.png') ?>" title="Remark">
            <span class="navbar-brand-text hidden-xs"> Remark</span>
        </div>
    </div>

    <div class="navbar-container container-fluid">
        <div class="collapse navbar-collapse navbar-collapse-toolbar" id="site-navbar-collapse">
            <ul class="nav navbar-toolbar">
                <li class="hidden-float" id="toggleMenubar">
                    <a data-toggle="menubar" href="#" role="button">
                        <i class="icon hamburger hamburger-arrow-left">
                            <span class="sr-only">Toggle menubar</span>
                            <span class="hamburger-bar"></span>
                        </i>
                    </a>
                </li>

                <li class="hidden-xs" id="toggleFullscreen">
                    <a class="icon icon-fullscreen" data-toggle="fullscreen" href="#" role="button">
                        <span class="sr-only">Toggle fullscreen</span>
                    </a>
                </li>

                <li class="dropdown dropdown-fw dropdown-mega">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="fade" role="button">
                        Mega <i class="icon wb-chevron-down-mini" aria-hidden="true"></i>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation">
                            <div class="mega-content">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <h5>UI Kit</h5>

                                        <ul class="blocks-2">
                                            <li class="mega-menu margin-0">
                                                <ul class="list-icons">
                                                    <li>
                                                        <i class="wb-chevron-right-mini" aria-hidden="true"></i>
                                                        <a href="#">Animation</a>
                                                    </li>
                                                </ul>
                                            </li>

                                            <li class="mega-menu margin-0">
                                                <ul class="list-icons">
                                                    <li>
                                                        <i class="wb-chevron-right-mini" aria-hidden="true"></i>
                                                        <a href="#">Modals</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="col-sm-4">
                                        <h5>Media</h5>

                                        <ul class="blocks-3">
                                            <li>
                                                <a class="thumbnail margin-0" href="javascript:void(0)">
                                                    <img class="width-full" src="<?php echo $this->basePath('dist/assets/images/view-1-150x100.jpg') ?>" />
                                                </a>
                                            </li>
                                        </ul>
                                    </div>

                                    <div class="col-sm-4">
                                        <h5 class="margin-bottom-0">Accordion</h5>

                                        <div class="panel-group panel-group-simple" id="siteMegaAccordion" aria-multiselectable="true" role="tablist">
                                            <div class="panel">
                                                <div class="panel-heading" id="siteMegaAccordionHeadingOne" role="tab">
                                                    <a class="panel-title" data-toggle="collapse" href="#siteMegaCollapseOne" data-parent="#siteMegaAccordion" aria-expanded="false" aria-controls="siteMegaCollapseOne">
                                                        Collapsible Group Item #1
                                                    </a>
                                                </div>
                                                <div class="panel-collapse collapse" id="siteMegaCollapseOne" aria-labelledby="siteMegaAccordionHeadingOne"
                                                     role="tabpanel">
                                                    <div class="panel-body">
                                                        De moveat laudatur vestra parum doloribus labitur sentire partes, eripuit praesenti
                                                        congressus ostendit alienae, voluptati ornateque
                                                        accusamus clamat reperietur convicia albucius.
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-toolbar navbar-right navbar-toolbar-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)" data-animation="scale-up" aria-expanded="false" role="button">
                        <span class="flag-icon flag-icon-<?php echo substr($this->locale()->current(), 0, 2) ?>"></span>
                        <?php
                            $locale = $this->locale()->all();
                            echo $locale[$this->locale()->current()];
                        ?>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <?php foreach($this->locale()->all() as $key => $value) : ?>
                            <li role="presentation">
                                <a href="<?php echo $this->url('app/admin/dashboard', ['locale' => $key]) ?>" role="menuitem">
                                    <span class="flag-icon flag-icon-<?php echo substr($key, 0, 2) ?>"></span>
                                    <?php echo $value ?>
                                </a>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                </li>

                <li class="dropdown">
                    <a class="navbar-avatar dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="false" data-animation="scale-up" role="button">
                        <span class="avatar avatar-online">
                            <img src="<?php echo $this->basePath('dist/assets/images/5.jpg') ?>" />
                            <i></i>
                        </span>
                    </a>

                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation">
                            <a href="javascript:void(0)" role="menuitem"><i class="icon wb-user" aria-hidden="true"></i> Profile</a>
                        </li>

                        <li class="divider" role="presentation"></li>

                        <li role="presentation">
                            <a href="<?php echo $this->url('logout') ?>" role="menuitem">
                                <i class="icon wb-power" aria-hidden="true"></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a data-toggle="dropdown" href="javascript:void(0)" title="Notifications" aria-expanded="false"
                       data-animation="scale-up" role="button">
                        <i class="icon wb-bell" aria-hidden="true"></i>
                        <span class="badge badge-danger up">5</span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
                        <li class="dropdown-menu-header" role="presentation">
                            <h5>NOTIFICATIONS</h5>
                            <span class="label label-round label-danger">New 5</span>
                        </li>

                        <li class="list-group" role="presentation">
                            <div data-role="container">
                                <div data-role="content">
                                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                                        <div class="media">
                                            <div class="media-left padding-right-10">
                                                <i class="icon wb-chat bg-orange-600 white icon-circle" aria-hidden="true"></i>
                                            </div>
                                            <div class="media-body">
                                                <h6 class="media-heading">Message received</h6>
                                                <time class="media-meta" datetime="2016-06-10T12:34:48+08:00">3 days ago</time>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>

                        <li class="dropdown-menu-footer" role="presentation">
                            <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                                <i class="icon wb-settings" aria-hidden="true"></i>
                            </a>
                            <a href="javascript:void(0)" role="menuitem">
                                All notifications
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a data-toggle="dropdown" href="javascript:void(0)" title="Messages" aria-expanded="false" data-animation="scale-up" role="button">
                        <i class="icon wb-envelope" aria-hidden="true"></i>
                        <span class="badge badge-info up">3</span>
                    </a>

                    <ul class="dropdown-menu dropdown-menu-right dropdown-menu-media" role="menu">
                        <li class="dropdown-menu-header" role="presentation">
                            <h5>MESSAGES</h5>
                            <span class="label label-round label-info">New 3</span>
                        </li>

                        <li class="list-group" role="presentation">
                            <div data-role="container">
                                <div data-role="content">
                                    <a class="list-group-item" href="javascript:void(0)" role="menuitem">
                                        <div class="media">
                                            <div class="media-left padding-right-10">
                                                <span class="avatar avatar-sm avatar-away">
                                                    <img src="<?php echo $this->basePath('dist/assets/images/5.jpg') ?>" />
                                                    <i></i>
                                                </span>
                                            </div>

                                            <div class="media-body">
                                                <h6 class="media-heading">Edward Fletcher</h6>

                                                <div class="media-meta">
                                                    <time datetime="2016-06-15T20:34:48+08:00">3 days ago</time>
                                                </div>

                                                <div class="media-detail">Dolor et irure cupidatat commodo nostrud nostrud.</div>
                                            </div>
                                        </div>
                                    </a>
                                </div>
                            </div>
                        </li>

                        <li class="dropdown-menu-footer" role="presentation">
                            <a class="dropdown-menu-footer-btn" href="javascript:void(0)" role="button">
                                <i class="icon wb-settings" aria-hidden="true"></i>
                            </a>

                            <a href="javascript:void(0)" role="menuitem">
                                See all messages
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

<div class="site-menubar">
    <div class="site-menubar-body">
        <div>
            <div>
                <div class="site-menubar-section">
                    <?php
                        $freeSpace  = disk_free_space('.');
                        $totalSpace = disk_total_space('.');

                        if (!function_exists('getdiskspace')) {
                            function getdiskspace($size)
                            {
                                $bytes = ['B', 'Kb', 'Mb', 'Gb', 'Tb'];
                                $i     = 0;

                                while (($size / 1024) > 1) {
                                    $size = $size / 1024;
                                    $i++;
                                }

                                return round($size, 1) . " " . $bytes[$i];
                            }
                        }

                        $free  = getdiskspace($freeSpace);
                        $total = getdiskspace($totalSpace);
                    ?>
                    <h5>
                        Spaces
                        <span class="pull-right"><?php echo $free . ' / ' . $total ?></span>
                    </h5>

                    <div class="progress progress-xs">
                        <div class="progress-bar active" style="width: <?php echo round(100 - ((100 * $freeSpace) / $totalSpace)) ?>%;" role="progressbar"></div>
                    </div>
                </div>

                <ul class="site-menu">
                    <?php echo $this->navigation('Zend\Navigation\Admin')->menu()->setPartial('admin/partial/menu'); ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="site-menubar-footer">
        <a href="javascript: void(0);" class="fold-show" data-placement="top" data-toggle="tooltip" data-original-title="Settings">
            <span class="icon wb-settings" aria-hidden="true"></span>
        </a>

        <a href="javascript: void(0);" data-placement="top" data-toggle="tooltip" data-original-title="Lock">
            <span class="icon wb-eye-close" aria-hidden="true"></span>
        </a>

        <a href="<?php echo $this->url('logout') ?>" data-placement="top" data-toggle="tooltip" data-original-title="Logout">
            <span class="icon wb-power" aria-hidden="true"></span>
        </a>
    </div>
</div>

<div class="site-gridmenu">
    <div>
        <div>
            <ul>
                <li>
                    <a href="#">
                        <i class="icon wb-envelope"></i>
                        <span>Mailbox</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="page animsition">
    <?php echo $this->content; ?>
</div>

<footer class="site-footer">
    <div class="site-footer-legal">
        © 2016 <a href="#">Remark</a>
    </div>

    <div class="site-footer-right">
        Crafted with <i class="red-600 wb wb-heart"></i> by <a href="http://themeforest.net/user/amazingSurge">amazingSurge</a>
    </div>
</footer>

<?php
echo $this->inlineScript()
    ->prependFile($this->basePath('dist/global/vendor/slidepanel/jquery-slidePanel.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/screenfull/screenfull.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/intro-js/intro.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/switchery/switchery.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/ashoverscroll/jquery-asHoverScroll.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/asscrollable/jquery.asScrollable.all.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/mousewheel/jquery.mousewheel.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/asscroll/jquery-asScroll.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/animsition/animsition.min.js'))
    ->prependFile($this->basePath('dist/global/vendor/bootstrap/bootstrap.min.js'));
echo $this->inlineComponent()
    ->prependFile($this->basePath('dist/global/js/components/switchery.min.js'))
    ->prependFile($this->basePath('dist/global/js/components/slidepanel.min.js'))
    ->prependFile($this->basePath('dist/global/js/components/animsition.min.js'))
    ->prependFile($this->basePath('dist/global/js/components/asscrollable.min.js'))
    ->prependFile($this->basePath('dist/assets/js/configs/config-tour.min.js'))
    ->prependFile($this->basePath('dist/global/js/configs/config-colors.min.js'))
    ->prependFile($this->basePath('dist/assets/js/sections/sidebar.min.js'))
    ->prependFile($this->basePath('dist/assets/js/sections/gridmenu.min.js'))
    ->prependFile($this->basePath('dist/assets/js/sections/menubar.min.js'))
    ->prependFile($this->basePath('dist/assets/js/sections/menu.min.js'))
    ->prependFile($this->basePath('dist/assets/js/site.min.js'))
    ->prependFile($this->basePath('dist/global/js/core.min.js'));
?>
<script>
    (function(document, window, $) {
        'use strict';

        var Site = window.Site;
        $(document).ready(function() {
            Site.run();
        });
    })(document, window, jQuery);
</script>
</body>
</html>